
include:
  - board: akdk_bt1
    shield: fing_board_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: akdk_bt1
    shield: fing_board_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: akdk_bt1
    shield: settings_reset

  - board: seeeduino_xiao_ble
    shield: fing_board_dongle dongle_screen
    #cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000 #optional if logging is enabled
    #snippet: zmk-usb-logging #only enable for debugging
    artifact-name: dongle-screen
  - board: seeeduino_xiao_ble
    shield: settings_reset
