include:
  - board: akdk_bt1
    shield: fing_board_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: akdk_bt1
    shield: fing_board_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: akdk_bt1
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: fing_board_dongle prospector_adapter
