# CONFIG_ZMK_STUDIO_LOCKING=n
# CONFIG_BT_CTLR_PHY_2M=n

# キーボードを Peripheral として動作させる
CONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=y
CONFIG_ZMK_BLE=y

# BLE 関連（必要なら）
# CONFIG_BT_MAX_CONN=1
# CONFIG_BT_MAX_PAIRED=1
